wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/infograph_train.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/infograph_test.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/painting_train.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/painting_test.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/quickdraw_train.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/quickdraw_test.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/real_train.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/real_test.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/sketch_train.txt
wget https://csr.bu.edu/ftp/visda/2019/multi-source/domainnet/txt/sketch_test.txt